
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: aibox-backend
    env_file: .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: aibox-frontend
    env_file: .env
    environment:
     - API_URL=http://backend:8000              # internal container-to-container
     - PUBLIC_BACKEND_BASE=http://localhost:8000 
    ports:
      - "${UI_PORT:-8501}:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
